aws_access_key_id: 'AKIAJ32OYZSIGU4HJGSA'
aws_secret_access_key: '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'
mysql_uri: 'mysql+pymysql://casoemaster:Casoe2019@casoe-gestion.cqwrg3r4zze2.eu-west-3.rds.amazonaws.com:3306/dbcasoe'
bucket_name: 'lstcmdcasoe'